services:
  stickerbot:
    build: .
    container_name: stickerwhatsappbot
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./.wwebjs_auth:/app/.wwebjs_auth
      # Uncomment below to persist session data
      # - ./.wwebjs_auth:/app/.wwebjs_auth
    environment:
      - NODE_ENV=production
    # ports:
    #   - "3000:3000" # Uncomment if your bot exposes a port
